### ISSUE TITLE
Login Not Working on Mobile

### ISSUE THREAD

**Issue by leedotpang** [PASSYpw/PASSY#10]
Hey! Amazing app, this is exactly what I was looking for to run on my local network for my wife and I. The only issue I found at all is that the form inputs on mobile (tested on iOS - iPhone 4s/Android BLU R1HD) seem to ignore the phone's keyboard. Any ideas?

**Comment by Scrumplex** [comment]
In the last git commit (b7aa55b9680032cd46697d18d0f10eadcd339511) the bug has been fixed. But the latest stable version of PASSY does not include the fix. You could clone the repo and have a probably unstable version of passy, but a backup of the database is always recommended before an upgrade.

EDIT: There is currently a bug with the two factor authentication feature documented in #11.

**Comment by Scrumplex** [comment]
The master branch of PASSY is slowly getting stable. After some testing we will release PASSY 2.0.3 which should fix this issue.

**Comment by Scrumplex** [comment]
Fixed in newest release. Don't forget to backup your old config when upgrading. (If you are hosting it)
