### ISSUE TITLE
2FA Recovery Code

### ISSUE THREAD

**Issue by Joshua2504** [PASSYpw/PASSY#13]
I would like to get an 2FA recovery code when I activate 2FA so I can still access my account in case I lost my Authy account (I know, that shouldn't happen, but you know...)

**Comment by Scrumplex** [comment]
There actually is one recovery code. It is shown on the last page on the 2FA-setup. It is just the private key used in the QR-code. If you loose your authenticator you can just enter the private key as the 2fa code

**Comment by Scrumplex** [comment]
But it looks like, I forgot to show a message, informing about the backup code. 

EDIT: Well... There is code for a message, just no call to show it. The message can be found at https://github.com/PASSYpw/PASSY/blob/3cdd546d5db14c7f5c1f69b0fe39938df1d8519e/page/page_user_settings.inc.php#L226

**Comment by Scrumplex** [comment]
Fixed by 42f95295cc5c288e1423eed9c57e5181a7df5202
